# -*- coding: utf-8 -*-
"""pythonproje_hangman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_OQInd-kQcE5G2VMFHci10819r-JmFq
"""

import random
name= input("Your name:")
pics = ["""
   +---+
   |   |
       |
       |
       |
       |
=========""","""
   +---+
   |   |
   O   |
       |
       |
       |
=========""","""
   +---+
   |   |
   O   |
   |   |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|   |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
  /    |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
  / \  |
       |
========="""]

while True:
    print(("-" * 30) + "\nHangman Game\n" + ("-" * 30))
    
    word = random.choice(["molecules", "python", "quantum", "biology", "biochemistry", "translation", "RNA", "DNA"])
    step = 0
    letters = []
    
    while True:
        print(pics[step])
        
        for i, char in enumerate(word):
            print(char if i in letters else "_"),
            
        answer = input("\nAnswer: ")
        
        if answer == word:
            print("You win!\n\n")
            break
        else:
            while True:
                rand = random.randint(0, len(word))
                if not rand in letters:
                    letters.append(rand)
                    break
            
            step += 1
        
        if step >= len(pics):
            print("You lose!\n\n")
            break
        
    if not "yes" == input("Do you want to play again? " ):
        break
    if "yes" == input("Do you want to play again? "):
          print("The Game will start")

import random
name= input("Your name:")
pics = ["""
   +---+
   |   |
       |
       |
       |
       |
=========""","""
   +---+
   |   |
   O   |
       |
       |
       |
=========""","""
   +---+
   |   |
   O   |
   |   |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|   |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
  /    |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
  / \  |
       |
========="""]

   while True:
    print(("-" * 30) + "\nHangman Game\n" + ("-" * 30))
    
    word = random.choice(["molecules", "python", "quantum", "biology", "biochemistry", "translation", "RNA", "DNA"])
    step = 0
    letters = []
    
while True:
        print(pics[step])
        
        for i, char in enumerate(word):
            print(char if i in letters else "_"),
            
        answer = input("\nAnswer: ")
        
        if answer == word:
            print("You win!\n\n")
            break
        else:
            while True:
                rand = random.randint(0, len(word))
                if not rand in letters:
                    letters.append(rand)
                    break
            
            step += 1
        
        if step >= len(pics):
            print("You lose!\n\n")
            break
        
        if "yes" == input("Do you want to play again? "):
          print("The Game will start")

import random
name= input("Your name:")
pics = ["""
   +---+
   |   |
       |
       |
       |
       |
=========""","""
   +---+
   |   |
   O   |
       |
       |
       |
=========""","""
   +---+
   |   |
   O   |
   |   |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|   |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
       |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
  /    |
       |
=========""","""
   +---+
   |   |
   O   |
  /|\  |
  / \  |
       |
========="""]


while True:
    print(("-" * 30) + "\nHangman Game\n" + ("-" * 30))
    
    word = random.choice(["molecules", "python", "quantum", "biology", "biochemistry", "translation", "RNA", "DNA"])
    step = 0
    letters = []
    
    while True:
        print(pics[step])
        
        for i, char in enumerate(word):
            print(char if i in letters else "_"),
            
        answer = input("\nAnswer: ")
        
        if answer == word:
            print("You win!\n\n")
            break
        else:
            while True:
                rand = random.randint(0, len(word))
                if not rand in letters:
                    letters.append(rand)
                    break
            
            step += 1
        
        if step >= len(pics):
            print("You lose!\n\n")
            break